Create Recipe Repository
qin-team-recipe/05-recipe-app pull request #50
Opened 2023-06-17 14:35 UTC by kkkkoki

## タスク URL
close #22 
# 作業内容
- [ ] create
- [ ] update
- [ ] paginate
- [ ] findById

# レビューにあたって参考にすべき情報（任意）
- favoriteCountだけoptionalにしましたが、他はそのままで大丈夫そうか
- entity.tsでzodのvalidationがこんな感じで良いのか

2023-06-18 02:18 UTC, Kazuki1131 requested changes

2023-06-18 02:18 UTC, Kazuki1131 commented on backend/prisma/schema.prisma
> +  favoriteCount Int?           @map("favorite_count") @db.UnsignedInt
favoriteCountは必ず`0以上の数値`が入るので、`null`は基本入らない形になります🙇

2023-06-18 03:40 UTC, kkkkoki commented on backend/prisma/schema.prisma
> +  favoriteCount Int?           @map("favorite_count") @db.UnsignedInt
ありがとうございます！修正します！

2023-06-18 11:09 UTC, kkkkoki commented on backend/src/infrastructure/repository/recipe/update.spec.ts
> +  });
@Kazuki1131 
ここのidが文字列じゃないor存在しないケースってuserIdでも書いた方が良いですかね？
```ts
  test('Update recipe with non-string id', async () => {
    // Exercise: call the function
    const recipeProps: RecipeUpdateInput = {
      id: updateResult.id,
      // ↓こんな感じ？
      userId: undefined,
      name: 'test name',
      description: 'test description',
      servingCount: 1,
      favoriteCount: 1,
    };
    const recipe = repository.update(recipeProps);
    await expect(recipe).rejects.toThrowError(
      new InvalidArgsError('id must be a string'),
    );
  });
```

2023-06-18 12:42 UTC, kkkkoki commented
@Kazuki1131 
test

2023-06-27 18:27 UTC, kkkkoki commented on backend/src/infrastructure/repository/recipe/find-many-by-user-id.spec.ts
> +  }).compile();
3. この書き方がおかしいと思っている

2023-06-27 18:30 UTC, kkkkoki commented on backend/src/infrastructure/repository/recipe/find-many-by-user-id.spec.ts
> +      );
1. userIdを渡すためにuserを作成して111行目で渡してみるようにしました

2023-06-27 18:32 UTC, kkkkoki commented on backend/src/infrastructure/repository/recipe/find-many-by-user-id.spec.ts
> +      expect(ormMock.recipe.findMany).toHaveBeenCalledWith(ormProps);
2. このテストが通らないので、50行目からの箇所がおかしいのかなと思った

2023-06-29 13:26 UTC, Kazuki1131 reviewed
動くかどうかテストはしてませんが、コメントしたようなイメージで実装してもらえれば大丈夫です！

2023-06-29 13:26 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/find-many-by-user-id.spec.ts
> +    };
以下のように変更お願いします！
```   
    const findIndexByRecipeId = (id: string, recipes: array): number => {
      return recipes.findIndex((recipe) => recipe.id === id);
    };
```

2023-06-29 13:26 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/find-many-by-user-id.spec.ts
> +
テストで`expect-found`のuserIdのみ取得できることを想定したテストデータを作成
```
const searchData = findManyByUserIdResults.map((recipe, index) => {
    return {
        ...recipe,
        userId: index % 2 === 0 : 'expect-found' : 'expect-not-found',
    }
})
```

2023-06-29 13:26 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/find-many-by-user-id.spec.ts
> +        });
以下に変更
```
        .mockImplementation(({ where: { userId }, take, cursor = {} }) => {
          const searched = searchData.filter((recipe) => recipe.userId === userId);
          const { id } = cursor;
          const start = id ? findIndexByRecipeId(id, searched) + 1 : 0;
          const end = start + take;
          const results = findManyByUserIdResults.filter((recipe) => {
              return searchData.find(({id}) => id === recipe.id);
          };
          return Promise.resolve(results);
        });
```

2023-07-05 12:04 UTC, kkkkoki commented
@Kazuki1131 
recipeのfindById実装したのですが、実装とテストケース[こんな](https://github.com/qin-team-recipe/05-recipe-app/pull/50/commits/33c08cf85438f42a9ba87dc3c880442c8c190ffc)感じで大丈夫そうですか？
あとuserがrecipeにいいねしているかの処理ってどこに実装する感じだったんでしょう…？

2023-07-08 03:39 UTC, Kazuki1131 requested changes
ご対応ありがとうございます！

2023-07-08 03:39 UTC, Kazuki1131 commented on backend/src/entity/recipe.entity.ts
> +  recipeItems: Pick<RecipeItem, 'name' | 'description'>[];
更新するときにidが必要になるので追加お願いできると助かります🙏

2023-07-08 03:39 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/find-by-id.spec.ts
> +      path: 'test/img/path1',
id追加に伴いfindResultのテストデータにもid追加お願いしますmm

2023-07-08 03:39 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/find-by-id.spec.ts
> +          path: true,
ここもid追加お願いしますmm

2023-07-08 03:39 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/find-by-id.spec.ts
> +  test('Find recipe with non-existent id', async () => {
LGTMです👍

2023-07-08 03:39 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/find-by-id.spec.ts
> +  test('Find recipe', async () => {
LGTMです👍

2023-07-08 03:39 UTC, Kazuki1131 commented on backend/src/infrastructure/repository/recipe/repository.ts
> +              path: true,
ここもidの追加お願いしますmm

2023-07-08 03:52 UTC, Kazuki1131 commented
> @Kazuki1131 recipeのfindById実装したのですが、実装とテストケース[こんな](https://github.com/qin-team-recipe/05-recipe-app/pull/50/commits/33c08cf85438f42a9ba87dc3c880442c8c190ffc)感じで大丈夫そうですか？ あとuserがrecipeにいいねしているかの処理ってどこに実装する感じだったんでしょう…？

すみません、いいねに関するコメント忘れてました！
いいねはFavoriteRepositoryを新しく作る形になります！
いいねとフォローは担当決めてなかったですが、kokiさんいいね機能やりますか？

2023-07-08 04:01 UTC, kkkkoki commented
@Kazuki1131 
ありがとうございます！！
一旦コメントしてもらった部分修正したのでご確認お願いします！
Kazukiさんの方で確認してもらってこのPR問題なさそうであればaproveお願いします🙏

> いいねはFavoriteRepositoryを新しく作る形になります！
いいねとフォローは担当決めてなかったですが、kokiさんいいね機能やりますか？

いいね機能は、このPRが問題なさそうであれば担当したいと思います！

2023-07-08 04:18 UTC, Kazuki1131 requested changes
1点だけ追加で修正お願いできると助かりますmm

2023-07-08 04:18 UTC, Kazuki1131 commented on backend/src/entity/recipe.entity.ts
> +export const RecipeUpdateInputSchema: z.ZodType<Prisma.RecipeUncheckedCreateInput> =
`Prisma.RecipeUncheckedCreateInput` -> `Prisma.RecipeUncheckedUpdateInput`にお願いしますmm

2023-07-08 04:25 UTC, kkkkoki commented
@Kazuki1131 
ご連絡ありがとうございます！！
修正しましたので、お願いします🙏

2023-07-08 04:26 UTC, Kazuki1131 approved these changes
ありがとうございます！マージしちゃいます！

2023-07-08 04:27 UTC, merged